pipeline {
    
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        
        stage('Checkout'){
           steps {
                sh 'echo "Checkout the code from SCM"'
                // git credentialsId: 'f87a34a8-0e09-45e7-b9cf-6dc68feac670', 
                // url: 'https://github.com/iam-veeramalla/cicd-end-to-end',
                // branch: 'main'
           }
        }

        stage('Build Docker'){
            steps{
                script{
                    sh '''
                    echo 'Buid Docker Image'
                    docker build -t mohansaravanan212/cicd-e2e:${BUILD_NUMBER} .
                    '''
                }
            }
        }

        stage('Push the artifacts'){
           steps{
                script{
                    withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                        sh '''
                        echo 'Push to Repo'
                        docker push mohansaravanan212/cicd-e2e:${BUILD_NUMBER}
                        '''
                    }
                }
            }
        }
        
        stage('Checkout K8S manifest SCM'){
            steps {
                sh 'echo "Checkout the K8S manifest from SCM"'
                // git credentialsId: 'f87a34a8-0e09-45e7-b9cf-6dc68feac670', 
                // url: 'https://github.com/iam-veeramalla/cicd-demo-manifests-repo.git',
                // branch: 'main'
            }
        }
        
        stage('Update K8S manifest & push to Repo'){
            steps {
                script{
                    // withCredentials([usernamePassword(credentialsId: 'f87a34a8-0e09-45e7-b9cf-6dc68feac670', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                        sh '''
                        cat python-jenkins-argocd-k8s/deploy/deploy.yaml
                        sed -i "s|image: mohansaravanan212/cicd-e2e:.*|image: mohansaravanan212/cicd-e2e:${BUILD_NUMBER}|" python-jenkins-argocd-k8s/deploy/deploy.yaml
                        cat python-jenkins-argocd-k8s/deploy/deploy.yaml
                        git add python-jenkins-argocd-k8s/deploy/deploy.yaml
                        git commit -m 'Updated the deploy yaml | Jenkins Pipeline'
                        git remote -v
                        git push -u origin main
                        '''                        
                    // }
                }
            }
        }
    }
}
