pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
        sh 'javac HelloWorld.java'
        sh 'java HelloWorld'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:20-alpine' }
      }
      steps {
        sh 'node --version'
        sh 'node hello.js'
      }
    }
    stage("Python-App"){
      agent any
      steps {
        sh 'docker build -t mohansaravanan212/my-flask-app:v1 .'
        sh 'docker push mohansaravanan212/my-flask-app:v1'
        sh 'docker run -d -p 5000:5000 mohansaravanan212/my-flask-app:v1'
      }
    }
  }
}
