pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
        sh 'javac HelloWorld.java'
        sh 'java HelloWorld'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
        sh 'node hello.js'
      }
    }
    stage("Pyhon-App"){
      agent {
        docker { image 'python:3.9-slim' }
      }
      steps {
        sh 'python --version'
        sh 'pip install -r requirements.txt'
        sh 'python hello.py'
      }
    }
  }
}
