pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
    // stage('Build') {
    //   steps {
    //     sh 'npm install'
    //     sh 'npm run build'
    //   }
    // }
    stage('Deploy') {
      steps {
        sh 'echo "Deploying application..."'
        sh 'echo "Deployment complete!"'
      }
    }
  }
}